<a href="https://colab.research.google.com/github/Katty7398/deber/blob/main/Actividad_3_de_Clase_01_nov_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MATRIZ RANGO 1 Y 2

In [ ]:
import numpy as np
aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)



aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))


tmp=np.zeros((4,4))
print(tmp)

tmp=np.full((4,4),5)
print(tmp)

tmp=np.eye(4,4)
print(tmp)

print("----------------")
tmp=np.ones((4,4))
print(tmp)

print(tmp.shape)


[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


MATRIZ 3*3

In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[6.0024621  6.36348353 1.59783524]
 [5.87235239 1.24315553 9.11014664]
 [6.30507848 9.8378046  9.86194672]]


FILA 0 Y FILA 1

In [ ]:
print(tmp[:2,:2])

[[6.0024621  6.36348353]
 [5.87235239 1.24315553]]


In [ ]:
print(tmp[:2,1:3])

[[6.36348353 1.59783524]
 [1.24315553 9.11014664]]


In [ ]:
print(tmp[1,1])

1.2431555283513485


In [ ]:
print(tmp[2,2])

9.86194671613455


filtrar datos


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[0.96298409 5.22654223 6.84802529]
 [9.20886781 8.27367577 2.96807272]
 [3.41008189 6.91393543 8.38241903]]


In [ ]:
mask=tmp>5
print(mask)

[[False  True  True]
 [ True  True False]
 [False  True  True]]


In [ ]:
mask=tmp>5
print(tmp[mask])

[5.22654223 6.84802529 9.20886781 8.27367577 6.91393543 8.38241903]


In [ ]:
mask = (tmp >= 2) & (tmp <= 4)
print(tmp[mask])

[2.96807272 3.41008189]


In [ ]:
integer_array = np.random.randint (0,10, (4,4))
print(integer_array)

[[2 3 0 0]
 [4 8 3 3]
 [9 9 3 3]
 [0 1 1 4]]


In [ ]:
# Crear una máscara booleana para los números pares
mascara_pares = integer_array % 2 == 0

# Filtrar los números pares utilizando la máscara
numeros_pares = integer_array[mascara_pares]

print("\nNúmeros pares:")
print(numeros_pares)



Números pares:
[2 0 0 4 8 0 4]
