<a href="https://colab.research.google.com/github/Katty7398/deber/blob/main/TAREA2_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MATRIZ RANGO 1 Y 2

In [ ]:
import numpy as np
aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)



aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))


tmp=np.zeros((4,4))
print(tmp)

tmp=np.full((4,4),5)
print(tmp)

tmp=np.eye(4,4)
print(tmp)

print("----------------")
tmp=np.ones((4,4))
print(tmp)

print(tmp.shape)


[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


MATRIZ 3*3

In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[6.0024621  6.36348353 1.59783524]
 [5.87235239 1.24315553 9.11014664]
 [6.30507848 9.8378046  9.86194672]]


FILA 0 Y FILA 1

In [ ]:
print(tmp[:2,:2])

[[6.0024621  6.36348353]
 [5.87235239 1.24315553]]


In [ ]:
print(tmp[:2,1:3])

[[6.36348353 1.59783524]
 [1.24315553 9.11014664]]


In [ ]:
print(tmp[1,1])

1.2431555283513485


In [ ]:
print(tmp[2,2])

9.86194671613455


filtrar datos


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[0.96298409 5.22654223 6.84802529]
 [9.20886781 8.27367577 2.96807272]
 [3.41008189 6.91393543 8.38241903]]


In [ ]:
mask=tmp>5
print(mask)

[[False  True  True]
 [ True  True False]
 [False  True  True]]


In [ ]:
mask=tmp>5
print(tmp[mask])

[5.22654223 6.84802529 9.20886781 8.27367577 6.91393543 8.38241903]


In [ ]:
mask = (tmp >= 2) & (tmp <= 4)
print(tmp[mask])

[2.96807272 3.41008189]


In [ ]:
integer_array = np.random.randint (0,10, (4,4))
print(integer_array)

[[2 3 0 0]
 [4 8 3 3]
 [9 9 3 3]
 [0 1 1 4]]


In [ ]:
# Crear una máscara booleana para los números pares
mascara_pares = integer_array % 2 == 0

# Filtrar los números pares utilizando la máscara
numeros_pares = integer_array[mascara_pares]

print("\nNúmeros pares:")
print(numeros_pares)



Números pares:
[2 0 0 4 8 0 4]


2matrices de **3x4**

In [1]:
import numpy as np
a= np.random.randint(1,11, size=(3,4))
b= np.random.randint(1,11, size=(3,4))
print(a)
print(b)
print(a.shape)
print("adding numbers")
print(a+b)

[[ 2  6  5  8]
 [ 3  9  4  2]
 [ 7  6  3 10]]
[[8 1 9 7]
 [8 4 2 4]
 [6 8 8 8]]
(3, 4)
adding numbers
[[10  7 14 15]
 [11 13  6  6]
 [13 14 11 18]]


In [2]:
import numpy as np
a= np.random.randint(1,11, size=(3,4))
b= np.random.randint(1,11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print("adding numbers")
print(a+b)
print("substracting numbers")
print(a-b)
print(np.add(a,b))
print(np.multiply(a,b))


[[10  6  4  1]
 [ 8  9  4  9]
 [ 5  7  7  9]]
[[2 2 4 1]
 [4 7 7 7]
 [3 2 2 4]]
(3, 4)
(3, 4)
adding numbers
[[12  8  8  2]
 [12 16 11 16]
 [ 8  9  9 13]]
substracting numbers
[[ 8  4  0  0]
 [ 4  2 -3  2]
 [ 2  5  5  5]]
[[12  8  8  2]
 [12 16 11 16]
 [ 8  9  9 13]]
[[20 12 16  1]
 [32 63 28 63]
 [15 14 14 36]]


In [3]:
a= np.random.randint(1,11, size=(2,3))
b= np.random.randint(1,11, size=(3,4))
print(a)
print(b)
print(np.dot(a,b))

[[6 3 9]
 [5 7 8]]
[[ 6  8  6  3]
 [ 9 10  6  4]
 [10  9  1  3]]
[[153 159  63  57]
 [173 182  80  67]]


In [4]:
a= np.random.randint(1,11, size=(2,3))
b= np.random.randint(1,11, size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[3 9 9]
 [2 8 9]]
[[ 8  6  5  4]
 [ 9  8  3  6]
 [10  8  4  4]]
[[195 162  78 102]
 [178 148  70  92]]
[[195 162  78 102]
 [178 148  70  92]]


In [5]:
a= np.random.randint(1,11, size=(2,2))
print(a.shape)
print(type(a))

(2, 2)
<class 'numpy.ndarray'>


In [6]:
a= np.random.randint(1,11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)


(2, 2)
<class 'numpy.ndarray'>
[[ 7 10]
 [ 1  7]]
[[ 7  1]
 [10  7]]


In [7]:
a= np.random.randint(1,11, size=(4,3))
b= np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('-------------')
print(c)
print('-------------')

for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)

(4, 3)
(3,)
[[ 4  1  4]
 [ 2  1  2]
 [10  5  7]
 [ 7  5  1]]
[1 0 2]
(4, 3)
-------------
[[10  6  4]
 [ 1  8  9]
 [ 4  9  5]
 [ 7  7  9]]
-------------
[[ 4  1  4]
 [ 2  1  2]
 [10  5  7]
 [ 7  5  1]]
[1 0 2]
[[ 5  1  6]
 [ 3  1  4]
 [11  5  9]
 [ 8  5  3]]


In [8]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
a=np.array([1,2,3])
print(a)
tmp=np.tile(a,(6,1))
print(tmp)
print('----------')
b=np.array([1,2,3])
print(b)
tmp=np.tile(a,(6,1))
print(tmp)
print('----------')
c=np.array([1,2,3])
print(c)
tmp=np.tile(a,(6,1))
print(tmp)
print('-----------')
d=np.array([1,2,3])
print(d)
tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
----------
[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
----------
[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
-----------
[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
a=np.random.randint(0, 10, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)

[[7 2 4 3 1 1]
 [8 8 4 4 8 3]
 [7 3 0 9 5 5]
 [2 3 4 7 3 0]
 [3 9 6 2 4 7]
 [2 6 7 8 4 9]]
4.666666666666667


In [11]:
a=np.random.randint(0, 10, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)

print(a.mean(axis=1))

[[2 0 8 0 8 7]
 [7 2 2 9 5 5]
 [5 4 0 6 3 4]
 [3 6 5 2 0 5]
 [1 2 7 8 0 2]
 [8 3 7 2 3 9]]
4.166666666666667
[4.16666667 5.         3.66666667 3.5        3.33333333 5.33333333]
